### ISSUE TITLE
Info.plist.in referencing icon.png which doesn't exist

### ISSUE THREAD

**Issue by Ribiveer** [Ravbug/sdl3-sample#2]
In Info.plist.in on line [36](https://github.com/Ravbug/sdl3-sample/blob/07953a80dca4fcd3425f18a86f49c6eed6598ff5/src/Info.plist.in#L36), a file called icon.png is referenced. However, there's only logo44.png, logo50.png, logo150.png and logo620x300.png in the repo. Looking through the commits, I believe this happened because XCode support was added before the logos were added, and the file name was speculative at the time.

**Comment by Ravbug** [comment]
Thanks!
