### ISSUE TITLE
How to build a SDL3 application to WebAssembly

### ISSUE THREAD

**Issue by 8Observer8** [Ravbug/sdl3-sample#3]
This is my topic on the SDL forum: https://discourse.libsdl.org/t/how-to-build-a-sdl3-application-to-webassembly/48041

I use this manual to build:
- Part 1: https://github.com/Ravbug/sdl3-sample/tree/main
- Part 2: https://github.com/Ravbug/sdl3-sample/blob/main/config/README.md

Note. This manual works for Android. Except "Ninja" app that must be installed (and added to Path, I used one from Qt: `C:\Qt\Tools\Ninja`) and manually changing of CMake version in the `build.gradle` script.

I installed the latest `emsdk` for the current time:

```
"emsdk.bat" install latest
"emsdk.bat" activate latest
```

I completed this task:
> 2. On Windows hosts, run `config-web-win.bat` via the `emcmdprompt.bat` cmd in the emsdk root directory

This is the result:

```
--   SDL_X11_XSHAPE              (Wanted: ON): OFF
--   SDL_XINPUT                  (Wanted: OFF): OFF
--
--  Build Shared Library: OFF
--  Build Static Library: ON
--  Build Static Library with Position Independent Code: OFF
--
-- If something was not detected, although the libraries
-- were installed, then make sure you have set the
-- CMAKE_C_FLAGS and CMAKE_PREFIX_PATH CMake variables correctly.
--
-- Configuring done (691.6s)
-- Generating done (0.3s)
-- Build files have been written to: E:/_Projects/SDL3/sdl3-sample/build/web
```

The next task is:

> 4. After the build completes, use python3 -m http.server in the build directory to make the page accessible.

But the `build` directory looks like this:

![image](https://github.com/Ravbug/sdl3-sample/assets/3908473/424f9871-ec7e-4649-bd39-ce37a58806de)

This is the `/build/web` directory:

![image](https://github.com/Ravbug/sdl3-sample/assets/3908473/a1a73a6c-e6c1-49ca-9175-5db625454c0a)

I have the `http-server` package to run the result but I don't see the index.html. What to do next? You should add the next step.

I ran the `mingw32-make` command inside of the `build/web` directory:

```
[ 95%] Building C object SDL/CMakeFiles/SDL3-static.dir/src/thread/generic/SDL_sysrwlock.c.o
[ 96%] Building C object SDL/CMakeFiles/SDL3-static.dir/src/thread/generic/SDL_syssem.c.o
[ 96%] Building C object SDL/CMakeFiles/SDL3-static.dir/src/thread/generic/SDL_systhread.c.o
[ 97%] Building C object SDL/CMakeFiles/SDL3-static.dir/src/thread/generic/SDL_systls.c.o
[ 97%] Linking C static library libSDL3.a
[ 97%] Built target SDL3-static
[ 98%] Building CXX object CMakeFiles/sdl-min.dir/src/main.cpp.o
[100%] Linking CXX executable sdl-min.html
error: linker: Undefined symbol: emscripten_webgl_get_proc_address(). Please pass -sGL_ENABLE_GET_PROC_ADDRESS at link time to link in emscripten_webgl_get_proc_address().
Error: Aborting compilation due to previous errors
em++: error: 'C:/emsdk/node/16.20.0_64bit/bin/node.exe C:\emsdk\upstream\emscripten\src\compiler.mjs C:\Users\8OBSER~1\AppData\Local\Temp\tmpwt4pmkp5.json' failed (returned 1)
mingw32-make[2]: *** [CMakeFiles\sdl-min.dir\build.make:100: sdl-min.html] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:101: CMakeFiles/sdl-min.dir/all] Error 2
mingw32-make: *** [Makefile:90: all] Error 2
```

Only the `sdl-min.wasm` was generated but I didn't find the `sdl-min.html` file. I don't understand what the errors mean and how to solve them.

![image](https://github.com/Ravbug/sdl3-sample/assets/3908473/40e496f3-36cd-4ff0-867b-0ed86f2fc72b)

**Comment by Ravbug** [comment]
This is an issue with Emscripten rather than with this sample. Possible fixes:
1. Use `tot` instead of `latest`, as `emscripten_webgl_get_proc_address` has been recently defaulted to enabled: https://github.com/emscripten-core/emscripten/commit/639e81720bab69aaaee5984563fb36960d6e88e0. This is demonstrated working here: https://github.com/Ravbug/sdl3-sample/actions/runs/7353720055/job/20020048005
2. Update your `CMakeLists.txt` to define `-sGL_ENABLE_GET_PROC_ADDRESS` as a linker flag, as per the error message
3. Wait until `tot` becomes mainline. Then `latest` should work correctly.

**Comment by 8Observer8** [comment]
Do you mean this CMakeLists.txt in the `sdl3-sample` directory?

![image](https://github.com/Ravbug/sdl3-sample/assets/3908473/12f5098a-7709-44ca-bcb5-7d09bfd758a5)

> define -sGL_ENABLE_GET_PROC_ADDRESS as a linker flag

I am to familiar with CMake. How to add this frag correctly? In what section?

**Comment by 8Observer8** [comment]
Why should I add the `-sGL_ENABLE_GET_PROC_ADDRESS` flag? It works without it:

The build process ended without errors:

![image](https://github.com/Ravbug/sdl3-sample/assets/3908473/a3dc45f0-e5cf-442d-ac57-edcad318d343)

I renamed the `sdl-min.html` to `index.html` and ran this command: `http-server -c-1` inside of the `build/web` directory. I opened this url: `http://localhost:8080/index.html` and it works:

![image](https://github.com/Ravbug/sdl3-sample/assets/3908473/99dac74e-106e-4453-b039-f61fb48a5981)

**Comment by 8Observer8** [comment]
I have written a step by step guide: [How to run SDL3 app on Web with WebAssembly on Windows](https://discourse.libsdl.org/t/my-step-by-step-guide-how-to-run-sdl3-app-on-web-with-webassembly-on-windows/50766)
