### ISSUE TITLE
Why the example shows a black screen in full screen mode?

### ISSUE THREAD

**Issue by 8Observer8** [Ravbug/sdl3-sample#6]
I deployed the example on the free hosting: https://65c7d7b5e53246a129d44cdc--silly-squirrel-b8f58f.netlify.app/

Why the example shows a black screen in full screen mode? How to solve it?

**Comment by Ravbug** [comment]
Please report this to the [SDL issue tracker](https://github.com/libsdl-org/SDL/issues).

**Comment by 8Observer8** [comment]
Done:

- Issue: https://github.com/libsdl-org/SDL/issues/9044
- Topic: https://discourse.libsdl.org/t/sdl3-webassebmly-doesnt-work-in-full-screen-mode/49132
